"""empty message

Revision ID: b16f60172eb5
Revises: None
Create Date: 2015-12-22 00:50:46.765289

"""

# revision identifiers, used by Alembic.
revision = 'b16f60172eb5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('fizz_buzz', sa.Integer(), nullable=False),
    sa.Column('record_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
